// Raidical portal content. Keep section edits local to this file.

export const ACQUIRER_PAGE_OVERVIEW = {
  title: 'Targets, Proof, and Current Market Flow',
  summary:
    'This page combines the target list and the market proof. The job is to show which firms are consolidating, how they appear to buy, and who is most likely to sponsor a small strategic acquisition.',
  bullets: [
    'Tier 1 and Tier 2 carry the deepest research because they sit closest to the workflow FIXFriend actually improves.',
    'Recent deals matter as pattern evidence, not as proof that FIXFriend is already positioned for purchase.',
    'When sourcing or adviser involvement is inferred rather than disclosed, the card says so explicitly.',
  ],
  marketFlow: [
    'Broadridge completed Acolin on January 6, 2026 and announced CQG on February 6, 2026.',
    'Trading Technologies acquired OpenGamma on December 17, 2025 after earlier expansion into fixed income through AxeTrading.',
    'SIX completed Aquis on July 1, 2025 and acquired Baymarkets on November 25, 2025.',
    'Deutsche Börse announced Allfunds on January 21, 2026 and the remaining ISS STOXX minority stake on February 11, 2026.',
  ],
}

export const ACQUIRERS = [
  {
    tier: 1,
    tierLabel: 'TRADING INFRASTRUCTURE VENDORS',
    tierSubtitle: 'Highest strategic fit',
    tierColor: 'green',
    acquirers: [
      {
        id: 'ion',
        logoKey: 'ion',
        name: 'ION Markets',
        ownership: 'Private',
        ownershipDetail: 'Founder-controlled',
        revenue: '$2.3B+',
        oneliner: 'OMS, EMS, and capital-markets workflow assets at scale',
        decisionSpeed: 'fast',
        owns: 'Fidessa, Broadway Technology, DASH, Clarus, and a broad workflow stack across front, middle, and post-trade capital-markets operations.',
        missing: 'No visible product layer owns venue notices, context recovery, certification coordination, and evidence generation as one response workflow.',
        strategicFit: 'ION already owns the plumbing. FIXFriend would sit above that stack as a thin venue-change response layer rather than another core platform.',
        howTheyBuy: 'Founder-led and centralized. As of March 2026, the public picture still points to tightly controlled strategic buying in adjacent workflow businesses, while current markets leadership remains harder to verify through official ION pages than through trade press and org-chart sources.',
        sourcingConfidence: 'Needs further diligence',
        recentDeals: [
          { label: 'Prelios', detail: 'Closed July 19, 2024 through X3, an ION subsidiary, for EUR 1.35bn.' },
          { label: 'Clarus Financial Technology', detail: 'Acquired September 10, 2021 to deepen cleared derivatives and post-trade capabilities.' },
        ],
        decisionMakers: [
          { name: 'Andrea Pignataro', role: 'Founder and CEO', note: 'Still the likely final sponsor for strategic acquisitions; confirmed through current ION corporate materials as of March 2026.' },
          { name: 'Silvio Oliviero', role: 'Head of Corporate Development and Chief Executive Officer for Markets', note: 'Risk.net reported this remit in April 2025; ION still lacks a clean public leadership page for the role, so this is verified through trade press and org-chart sources as of March 2026.' },
        ],
        sourceLinks: [
          { label: 'ION closes Prelios acquisition (Andrea Pignataro current sponsor signal)', url: 'https://iongroup.com/press-release/group/ion-group-announces-closing-of-prelios-acquisition/' },
          { label: 'Risk.net reports Silvio Oliviero as ION markets CEO and corp-dev lead (Apr 2025)', url: 'https://www.risk.net/people/7961384/caramanli-quits-ion-destination-unknown' },
          { label: 'The Org lists Silvio Oliviero in corporate development at ION (checked Mar 2026)', url: 'https://theorg.com/org/ion-group/org-chart/silvio-oliviero' },
          { label: 'ION acquires Clarus', url: 'https://iongroup.com/press-release/markets/ion-acquires-clarus-financial-technology/' },
        ],
      },
      {
        id: 'broadridge',
        logoKey: 'broadridge',
        name: 'Broadridge',
        ownership: 'Public',
        ownershipDetail: 'NYSE: BR',
        revenue: '$5B+',
        oneliner: 'Connectivity, OMS, onboarding, execution, and distribution',
        decisionSpeed: 'medium',
        owns: 'Connectivity and order management through BTCS, including Itiviti, ULLINK, Tbricks, VeriFIX, managed FIX services, and NYFIX. Execution is expanding through CQG. Distribution expanded through Acolin.',
        missing: 'VeriFIX covers onboarding and testing, but there is still no agent layer that sources specs, classifies change, coordinates minor versus major work, and preserves live evidence across the workflow.',
        strategicFit: 'Broadridge is the cleanest stack fit. Connectivity, OMS, execution, onboarding, and distribution are already there; FIXFriend would add response orchestration rather than another core system.',
        howTheyBuy: 'The public signal is relationship-led platform expansion. Broadridge announced a strategic integration with CQG in November 2025 and followed with a full acquisition agreement on February 6, 2026.',
        sourcingConfidence: 'Relationship-led',
        recentDeals: [
          { label: 'Acolin', detail: 'Completed January 6, 2026 to expand fund distribution infrastructure.' },
          { label: 'CQG', detail: 'Acquisition announced February 6, 2026 after a prior strategic integration announcement in November 2025.' },
        ],
        decisionMakers: [
          { name: 'Chris Perry', role: 'President', note: 'Verified on Broadridge’s leadership page as of March 2026; his remit still includes international expansion and corporate development.' },
          { name: 'Vincent G. Roux', role: 'Senior Vice President, Global Head of Corporate Development', note: 'Verified on Broadridge’s leadership page as of March 2026; the cleanest current corp-dev contact for a tuck-in discussion.' },
          { name: 'Frank Troise', role: 'President, BTCS and Head of Global Technology and Operations', note: 'Verified on Broadridge’s leadership page as of March 2026; still closest to the trading/connectivity stack where FIXFriend would attach.' },
        ],
        sourceLinks: [
          { label: 'Broadridge leadership team (Chris Perry, Vincent G. Roux, Frank Troise checked Mar 2026)', url: 'https://www.broadridge.com/our-leadership-team' },
          { label: 'Broadridge completes Acolin', url: 'https://www.broadridge.com/press-release/2026/broadridge-completes-acquisition-of-acolin' },
          { label: 'Broadridge to acquire CQG', url: 'https://www.broadridge.com/press-release/2026/broadridge-enters-into-agreement-to-acquire-cqg' },
          { label: 'Broadridge and CQG strategic integration', url: 'https://www.broadridge.com/press-release/2025/broadridge-and-cqg-enter-into-strategic-technology-integration-agreement' },
          { label: 'Broadridge completes Itiviti acquisition', url: 'https://www.prnewswire.com/news-releases/broadridge-completes-acquisition-of-itiviti-301312894.html' },
        ],
      },
      {
        id: 'murex',
        logoKey: 'murex',
        name: 'Murex',
        ownership: 'Private',
        ownershipDetail: 'Founder-led',
        revenue: 'Undisclosed',
        revenueNote: 'estimates remain wide',
        oneliner: 'MX.3 trading, risk, collateral, and MXSaaS platform',
        decisionSpeed: 'fast',
        owns: 'MX.3 across trading, risk, collateral, treasury, and investment management, with a strong managed-services and cloud migration push through MXSaaS.',
        missing: 'The pain exists in the client base, but public evidence still points more to organic build and partnerships than to active acquisitions in this niche.',
        strategicFit: 'This is a fit story more than an M&A-pattern story. Murex faces the right workflow problem, but the public acquisition signal is weak.',
        howTheyBuy: 'Publicly, Murex currently looks independence-led and partnership-led. The official signal is organic expansion around MX.3 and MXSaaS rather than visible acquisitions.',
        sourcingConfidence: 'Needs further diligence',
        recentDeals: [
          { label: 'AWS collaboration', detail: 'Announced September 29, 2025 as a strategic multi-year collaboration to scale managed services.' },
          { label: 'Alveo partnership', detail: 'Announced March 5, 2024 to strengthen data-rich investment-management workflows.' },
        ],
        decisionMakers: [
          { name: 'Elias Eddé', role: 'Chief Executive Officer', note: 'Verified through Murex’s governance-transition announcement as of March 2026; current operating leader and likely sponsor if M&A posture changes.' },
          { name: 'Maroun Eddé', role: 'Executive Chairman', note: 'Verified through the same governance-transition announcement as of March 2026; still central to strategic direction and governance.' },
        ],
        sourceLinks: [
          { label: 'Murex governance transition (Elias Eddé and Maroun Eddé checked Mar 2026)', url: 'https://www.murex.com/en/news/murex-elias-edde-takes-ceo-role-financial-technology-leader-governance-transition-maroun-edde' },
          { label: 'Murex and AWS collaboration', url: 'https://www.murex.com/en/news/murex-announces-strategic-multi-year-global-aws-collaboration-agreement-accelerate-ambitious' },
          { label: 'Murex and Alveo partnership', url: 'https://www.murex.com/en/news/murex-alveo-partner-provide-comprehensive-data-driven-ims-solution' },
        ],
      },
      {
        id: 'tt',
        logoKey: 'tt',
        name: 'Trading Technologies',
        ownership: 'Private',
        ownershipDetail: '7RIDGE-backed',
        revenue: 'Undisclosed',
        oneliner: 'Execution, analytics, compliance, and multi-asset workflow expansion',
        decisionSpeed: 'fast',
        owns: 'Derivatives execution infrastructure, multi-venue connectivity, compliance and surveillance tooling, and a growing analytics layer across listed and OTC workflows.',
        missing: 'The platform reaches 100+ exchanges, but FIXFriend’s venue-change coordination layer is still absent from the stack.',
        strategicFit: 'TT already knows how to buy adjacent workflow technology. FIXFriend fits as a small control product inside a platform that already lives close to the venue edge.',
        howTheyBuy: 'Executive-sponsored platform expansion backed by sponsor capital. Public acquisitions show targeted product and analytics tuck-ins; adviser involvement on larger deals is plausible but not disclosed in the linked sources.',
        sourcingConfidence: 'Needs further diligence',
        recentDeals: [
          { label: 'OpenGamma', detail: 'Acquired December 17, 2025 to add margin and capital optimization analytics.' },
          { label: 'AxeTrading', detail: 'Acquired January 12, 2023 to accelerate multi-asset expansion into fixed income.' },
        ],
        decisionMakers: [
          { name: 'Justin Llewellyn-Jones', role: 'Chief Executive Officer', note: 'Verified on TT’s management page as of March 2026; the most visible executive sponsor for platform expansion.' },
          { name: 'Jason Shaffer', role: 'Chief Technology and Product Officer', note: 'Verified on TT’s management page as of March 2026; still the clearest product-side sponsor for adjacent workflow acquisitions.' },
          { name: 'Chris Heffernan', role: 'EVP and Managing Director, Fixed Income', note: 'Verified on TT’s management page and recent fixed-income releases as of March 2026; a better workflow-adjacent sponsor than the finance function for FIXFriend.' },
        ],
        sourceLinks: [
          { label: 'TT acquires OpenGamma', url: 'https://tradingtechnologies.com/news-releases/trading-technologies-acquires-opengamma-leader-in-margin-and-capital-optimization-analytics/' },
          { label: 'TT CEO transition', url: 'https://tradingtechnologies.com/news-releases/trading-technologies-promotes-justin-llewellyn-jones-to-ceo-keith-todd-to-deputy-chairman/' },
          { label: 'TT management team (Justin Llewellyn-Jones, Jason Shaffer, Chris Heffernan checked Mar 2026)', url: 'https://tradingtechnologies.com/about-us/meet-the-team/' },
          { label: 'TT fixed-income release quoting Chris Heffernan', url: 'https://tradingtechnologies.com/news-releases/trading-technologies-wins-editors-choice-award-for-outstanding-market-data-services-provider-fixed-income-in-the-trades-leaders-in-trading-2024-awards/' },
          { label: 'TT acquires AxeTrading', url: 'https://tradingtechnologies.com/news-releases/trading-technologies-acquires-axetrading-further-accelerating-multi-asset-class-expansion-with-major-move-into-fixed-income-markets/' },
        ],
      },
    ],
  },
  {
    tier: 2,
    tierLabel: 'EXCHANGE GROUPS',
    tierSubtitle: 'Venue operators with certification bottlenecks',
    tierColor: 'blue',
    acquirers: [
      {
        id: 'six',
        logoKey: 'six',
        name: 'SIX Group',
        ownership: 'Private',
        ownershipDetail: 'Swiss bank-owned',
        revenue: '~CHF 1.6B',
        oneliner: 'Exchanges, post-trade, and pan-European market structure buildout',
        decisionSpeed: 'fast',
        owns: 'SIX Swiss Exchange, BME, Aquis, post-trade infrastructure, and securities services spanning multiple European market structures.',
        missing: 'No visible product layer automates member-facing certification, protocol evidence, and cross-venue change response at group scale.',
        strategicFit: 'SIX is now one of the clearest exchange-side fits. More venues and more post-trade technology mean more member certification complexity.',
        howTheyBuy: 'Executive-led exchange and post-trade expansion. Public releases show a direct pattern of buying core market-structure assets and integrating them into the group platform.',
        sourcingConfidence: 'Publicly disclosed',
        recentDeals: [
          { label: 'Aquis Exchange', detail: 'Completed July 1, 2025, extending SIX across 16 EU and UK markets.' },
          { label: 'Baymarkets', detail: 'Acquired November 25, 2025 to modernize clearing technology.' },
        ],
        decisionMakers: [
          { name: 'Bjørn Sibbern', role: 'Chief Executive Officer', note: 'Verified through SIX governance materials and the 2024 annual report as of March 2026; primary executive sponsor for group strategy.' },
          { name: 'Tomas Kindler', role: 'Global Head Exchanges', note: 'Verified through SIX governance materials and the 2024 annual report as of March 2026; the clearest venue-side sponsor for exchange and certification workflow gaps.' },
          { name: 'David Brupbacher', role: 'Head IT and Member of the Executive Board', note: 'Verified through SIX’s March 2024 appointment release and the 2024 annual report as of March 2026; closer to implementation and integration risk than the finance seat.' },
        ],
        sourceLinks: [
          { label: 'SIX completes acquisition of Aquis', url: 'https://www.six-group.com/en/newsroom/media-releases/2025/20250701-completion-acquisition-aquis.html' },
          { label: 'SIX acquires Baymarkets', url: 'https://www.six-group.com/en/newsroom/media-releases/2025/20251125-baymarkets-acquisition.html' },
          { label: 'SIX executive board (Bjørn Sibbern, Tomas Kindler, David Brupbacher checked Mar 2026)', url: 'https://www.six-group.com/en/company/governance/executive-board.html' },
          { label: 'SIX annual report 2024 organizational structure', url: 'https://www.six-group.com/dam/download/company/report/annual/2024/six-annual-report-2024-en.pdf' },
          { label: 'SIX appoints David Brupbacher to executive board', url: 'https://www.six-group.com/en/newsroom/media-releases/2024/20240308-six-exb-mutation.html' },
          { label: 'SIX board of directors', url: 'https://www.six-group.com/en/company/governance/board-of-directors.html' },
        ],
      },
      {
        id: 'dbg',
        logoKey: 'deutsche-boerse',
        name: 'Deutsche Börse',
        ownership: 'Public',
        ownershipDetail: 'ETR: DB1',
        revenue: '€4B+',
        oneliner: 'Exchange, clearing, index, software, and investment-management infrastructure',
        decisionSpeed: 'slow',
        owns: 'Eurex, Xetra, Clearstream, ISS STOXX, SimCorp, and a broad investment-management software and data stack.',
        missing: 'The strategic fit is credible, but the path is formal and slower. No public signal suggests a push into small workflow acquisitions around venue certification.',
        strategicFit: 'The problem exists inside the Eurex ecosystem, but this is a longer-cycle public-company path rather than a fast tuck-in target.',
        howTheyBuy: 'Formal public-company M&A with stated value-accretive logic. The linked sources support disciplined strategic acquisitions; adviser mix is not disclosed here and should be treated as inference.',
        sourcingConfidence: 'Needs further diligence',
        recentDeals: [
          { label: 'Allfunds Group', detail: 'Recommended acquisition agreement announced January 21, 2026.' },
          { label: 'ISS STOXX minority stake', detail: 'Agreed February 11, 2026 to acquire the remaining 20% minority stake from General Atlantic.' },
        ],
        decisionMakers: [
          { name: 'Stephan Leithner', role: 'Chief Executive Officer', note: 'Verified on Deutsche Börse executive materials as of March 2026; top-level strategic sponsor.' },
          { name: 'Thomas Book', role: 'Member of the Executive Board, Trading and Clearing', note: 'Verified on Deutsche Börse management pages as of March 2026; closest public executive owner to Eurex and the venue workflow problem.' },
          { name: 'Christoph Böhm', role: 'Chief Information Officer / Chief Operating Officer', note: 'Verified by Deutsche Börse’s December 2025 board-mandate extension as of March 2026; the strongest technology and operations sponsor for workflow-control software.' },
        ],
        sourceLinks: [
          { label: 'Deutsche Börse and Allfunds agreement', url: 'https://www.deutsche-boerse.com/dbg-en/media/news-stories/press-releases/Deutsche-B-rse-Group-and-Allfunds-Group-Sign-Agreement-on-Recommended-Acquisition-of-Allfunds-Group-4914918' },
          { label: 'Deutsche Börse acquires ISS STOXX minority stake', url: 'https://www.deutsche-boerse.com/dbg-en/media/news-stories/press-releases/Deutsche-B-rse-Group-to-Acquire-General-Atlantic-s-Minority-Stake-in-ISS-STOXX-4948682' },
          { label: 'Deutsche Börse executive board (Stephan Leithner checked Mar 2026)', url: 'https://www.deutsche-boerse.com/dbg-en/about-us/deutsche-boerse-group/executive-board' },
          { label: 'Deutsche Börse market data management page for Thomas Book', url: 'https://www.mds.deutsche-boerse.com/mds-en/about-us/management' },
          { label: 'Deutsche Börse extends Christoph Böhm board mandate (Dec 2025)', url: 'https://www.deutsche-boerse.com/dbg-en/media/news-stories/press-releases/Supervisory-Board-of-Deutsche-B-rse-AG-Extends-Executive-Board-Mandate-of-Christoph-B-hm-4839418' },
        ],
      },
      {
        id: 'euronext',
        logoKey: 'euronext',
        name: 'Euronext',
        ownership: 'Public',
        ownershipDetail: 'Pan-European exchange',
        revenue: '€1.5B+',
        oneliner: 'Federal market infrastructure model with active strategic development',
        decisionSpeed: 'medium',
        owns: 'Pan-European cash, derivatives, clearing, and software infrastructure across multiple national markets.',
        missing: 'There is clear strategic-development capacity, but the specific fit to venue-change workflow still needs proof through direct conversations.',
        strategicFit: 'Euronext has the right structural problem: multiple markets, multiple protocol variants, and a public M&A machine that already integrates recurring infrastructure businesses.',
        howTheyBuy: 'Strategy-led M&A is visible publicly. As of March 2026, Camille Beudin remains the clearest named strategic-development contact even after moving into the chief diversification role, and the federal model still makes small infrastructure tuck-ins plausible when they fit the broader platform.',
        sourcingConfidence: 'Publicly disclosed',
        recentDeals: [
          { label: 'Admincontrol', detail: 'Completed May 13, 2025 to add recurring software revenue.' },
          { label: 'ATHEX Group', detail: 'Successful tender announced November 19, 2025, reaching about 74.25% of voting rights.' },
        ],
        decisionMakers: [
          { name: 'Stéphane Boujnah', role: 'Chief Executive Officer and Chairman of the Managing Board', note: 'Verified on Euronext governance materials as of March 2026; visible top-level sponsor for strategic direction.' },
          { name: 'Camille Beudin', role: 'Chief Diversification Officer', note: 'Verified on Euronext governance materials and 2025 company materials as of March 2026; still publicly tied to strategic development and M&A even after the title change.' },
          { name: 'Anthony Attia', role: 'Global Head of Derivatives and Post-Trade', note: 'Verified in recent 2025-2026 Euronext releases as of March 2026; much closer than finance to the venue, clearing, and certification workflow FIXFriend addresses.' },
        ],
        sourceLinks: [
          { label: 'Euronext full-year 2025 results', url: 'https://www.euronext.com/en/investor-relations/financial-information/news/euronext-publishes-q4-and-full-year-2025-results' },
          { label: 'Euronext and Admincontrol announcement', url: 'https://www.euronext.com/sites/default/files/2025-03/20250313_Euronext%20Admincontrol%20announcement.pdf' },
          { label: 'Euronext announces success of ATHEX exchange offer', url: 'https://www.euronext.com/en/investor-relations/financial-information/news/euronext-announces-success-voluntary-share-exchange' },
          { label: 'Euronext to acquire Nasdaq Nordic power futures business', url: 'https://www.euronext.com/en/about/media/euronext-press-releases/euronext-acquire-nasdaqs-nordic-power-futures-business' },
          { label: 'Euronext managing board (Stéphane Boujnah and Camille Beudin checked Mar 2026)', url: 'https://www.euronext.com/en/investor-relations/corporate-governance/managing-board' },
          { label: 'Euronext release quoting Anthony Attia as global head of derivatives and post-trade', url: 'https://www.euronext.com/en/about/media/euronext-press-releases/euronext-and-clearstream-launch-partnership-further-strengthen' },
        ],
      },
    ],
  },
  {
    tier: 3,
    tierLabel: 'REGTECH / COMPLIANCE ADJACENCY',
    tierSubtitle: 'Same buyer, lighter probability',
    tierColor: 'indigo',
    acquirers: [
      {
        id: 'kaizen',
        logoKey: 'kaizen',
        name: 'Kaizen Reporting',
        ownership: 'PE-backed',
        ownershipDetail: 'Guidepost Growth Equity',
        revenue: 'Private',
        oneliner: 'Regulatory reporting testing and surveillance',
        decisionSpeed: 'fast',
        owns: 'Regulatory reporting accuracy testing, control evidence, and transaction surveillance.',
        missing: 'Adjacent buyer, but not the core venue-change workflow owner today.',
        strategicFit: 'Possible adjacency play if FIXFriend is framed as evidence and control infrastructure rather than exchange workflow.',
      },
      {
        id: 'smartstream',
        logoKey: 'smartstream',
        name: 'SmartStream Technologies',
        ownership: 'Sovereign wealth-backed',
        ownershipDetail: 'ICD-owned',
        revenue: '~£43M',
        revenueNote: 'FY2023',
        oneliner: 'Reconciliation, controls, and post-trade operations',
        decisionSpeed: 'medium',
        owns: 'Reconciliation, post-trade controls, and reference data management.',
        missing: 'Still further from front-office venue-change response than Tier 1 or Tier 2 targets.',
        strategicFit: 'More plausible as a control-adjacency conversation than as a primary acquirer target.',
      },
      {
        id: 'exactpro',
        logoKey: 'exactpro',
        name: 'Exactpro',
        ownership: 'Private',
        ownershipDetail: 'Independent specialist',
        revenue: 'Private',
        oneliner: 'Testing and QA for exchanges and trading venues',
        decisionSpeed: 'fast',
        owns: 'Testing and QA services for exchanges, venues, and trading systems.',
        missing: 'Strong on testing, weaker on owning the full workflow from notice to rollout to evidence.',
        strategicFit: 'Best treated as product adjacency, integration path, or talent-rich partner target.',
      },
      {
        id: 'quod',
        logoKey: 'quod',
        name: 'Quod Financial',
        ownership: 'Private',
        ownershipDetail: 'Founder-led / independent',
        revenue: 'Undisclosed',
        oneliner: 'Multi-asset OMS, EMS, SOR, and pre-trade automation',
        decisionSpeed: 'medium',
        owns: 'Multi-asset OMS/OEMS, smart order routing, algorithmic execution, pre-trade automation, auditability, and broad front-to-middle-office trading workflows.',
        missing: 'No visible layer owns venue notices, context recovery, certification coordination, and evidence generation as one dedicated response workflow.',
        strategicFit: 'Quod is a real product fit. FIXFriend would attach naturally to an OMS/EMS and automation stack already used by banks, brokers, and liquidity providers.',
        howTheyBuy: 'Publicly, Quod looks product-led and expansion-led rather than visibly acquisitive. Strategic fit is strong, but public evidence for acquisition pace or financing appetite is limited and should be treated as diligence work, not assumption.',
        sourcingConfidence: 'Needs further diligence',
        recentDeals: [
          { label: 'Co-CEO transition', detail: 'Medan Gabbay was appointed Co-CEO effective March 21, 2025, signaling a broader leadership structure as the company scales.' },
          { label: 'North American expansion', detail: 'Quod announced a New York head-of-sales hire in July 2024, which supports expansion intent but not a disclosed M&A pattern.' },
        ],
        decisionMakers: [
          { name: 'Ali Pichvai', role: 'Co-CEO and Founder', note: 'Still current as of March 2026: Quod’s March 17, 2025 co-CEO announcement names him as Co-CEO and founder, and his March 3, 2026 authored article confirms he remains active even though the current About page spotlights other operators.' },
          { name: 'Medan Gabbay', role: 'Co-CEO', note: 'Verified through Quod’s March 17, 2025 announcement and current About page as of March 2026; deep product and commercial operator with current leadership authority across the platform.' },
          { name: 'Ben Ernest-Jones', role: 'Chief Product & Technology Officer', note: 'Verified on Quod’s current About page and recent 2026 article byline as of March 2026; the strongest product-side sponsor for workflow-control discussions.' },
        ],
        sourceLinks: [
          { label: 'Quod homepage and product overview', url: 'https://www.quodfinancial.com/' },
          { label: 'Quod OMS overview', url: 'https://www.quodfinancial.com/order-management-system-oms/' },
          { label: 'Quod Equities O/EMS overview', url: 'https://www.quodfinancial.com/markets/equities-oms/' },
          { label: 'Quod announces Medan Gabbay as Co-CEO and names Ali Pichvai as Co-CEO and founder', url: 'https://www.quodfinancial.com/medan-gabbay-co-ceo-appointment/' },
          { label: 'Quod About page (Medan Gabbay and Ben Ernest-Jones checked Mar 2026)', url: 'https://www.quodfinancial.com/about-us/' },
          { label: 'Ali Pichvai authored Quod article on 3 Mar 2026', url: 'https://www.quodfinancial.com/ai-cambrian-explosion-software/' },
          { label: 'Quod news and press', url: 'https://www.quodfinancial.com/resources/news-press/' },
        ],
      },
    ],
  },
  {
    tier: 4,
    tierLabel: 'LONG-SHOT / OPTIONALITY',
    tierSubtitle: 'Lower probability and longer cycles',
    tierColor: 'indigo',
    acquirers: [
      {
        id: 'nasdaq',
        logoKey: 'nasdaq',
        name: 'NASDAQ',
        ownership: 'Public',
        ownershipDetail: 'NASDAQ: NDAQ',
        revenue: '$6B+',
        oneliner: 'Exchange, market tech, surveillance, and Adenza',
        decisionSpeed: 'slow',
        owns: 'Exchanges, surveillance, matching and clearing technology, and the Adenza risk and regtech stack.',
        missing: 'Not visibly building the specific venue-change workflow layer FIXFriend addresses.',
        strategicFit: 'Strategically relevant, but not a near-term target while digestion of larger acquisitions continues.',
      },
      {
        id: 'lseg',
        logoKey: 'lseg',
        name: 'LSEG',
        ownership: 'Public',
        ownershipDetail: 'London Stock Exchange Group',
        revenue: '£8B+',
        oneliner: 'Exchange, data, post-trade, and workflow distribution',
        decisionSpeed: 'slow',
        owns: 'Trading venues, Refinitiv, FTSE Russell, LCH, and post-trade technology.',
        missing: 'The gap is visible, but the likely buy path is long and selective.',
        strategicFit: 'Optional long-range fit if LSEG pushes further into agent-assisted operational workflows.',
      },
      {
        id: 'factset',
        logoKey: 'factset',
        name: 'FactSet',
        ownership: 'Public',
        ownershipDetail: 'NYSE: FDS',
        revenue: '$2B+',
        oneliner: 'Data, analytics, OMS, and compliance adjacencies',
        decisionSpeed: 'medium',
        owns: 'Research, analytics, LiquidityBook, and a growing compliance tooling footprint.',
        missing: 'Still one step removed from the venue-certification problem.',
        strategicFit: 'Interesting only if the compliance and workflow thesis broadens materially.',
      },
    ],
  },
]

export const DEALS = [
  {
    id: 'cinven-objectway',
    logoKey: 'cinven',
    date: '7 Aug 2025',
    dateSort: '2025-08-07',
    acquirer: 'Cinven',
    target: 'Objectway',
    status: 'Closed Nov 2025',
    acquirerType: 'Private Equity',
    timeline: '~3 months',
    dealLogic:
      'Majority stake in wealth management software. 250+ financial institution clients. Accelerate growth via M&A. First investment from Cinven\'s new mid-market strategy.',
    pattern:
      'PE firms moving fast in European financial software. Private capital sees regulatory compliance automation as a growth enabler.',
    relevance: null,
  },
  {
    id: 'iress',
    logoKey: 'iress',
    date: 'Aug 2025',
    dateSort: '2025-08-15',
    acquirer: 'Blackstone / Thoma Bravo',
    target: 'IRESS',
    status: 'In play',
    acquirerType: 'Private Equity',
    timeline: 'Active',
    dealLogic:
      'Trading and wealth software. ~AU$600M revenue. UK EBITDA up 43% YoY. Core business is trading & market data — directly relevant to venue connectivity compliance.',
    pattern:
      'Any acquirer of IRESS inherits a business where venue connectivity compliance is a daily operational reality. Compliance tooling strengthens the acquisition value.',
    relevance:
      'Blackstone and Thoma Bravo both circling. Additional unnamed parties engaged.',
  },
  {
    id: 'six-aquis',
    logoKey: 'six',
    date: 'Nov 2024 → Jul 2025',
    dateSort: '2025-07-01',
    acquirer: 'SIX Group',
    target: 'Aquis Exchange',
    status: 'Closed 1 Jul 2025',
    acquirerType: 'Private (Swiss bank-owned)',
    timeline: '~8 months',
    dealValue: '~£207M',
    dealLogic:
      'Create pan-European exchange innovator. 15% aggregated market share. 16 capital markets. Only exchange group with listing venues in Switzerland, EU, and UK.',
    pattern:
      'Exchange consolidation directly amplifies the problem FIXFriend solves. More venues under one roof = more certification complexity for members.',
    relevance:
      'SIX now operates multiple venues with different protocols. Member certification across all venues is a massive operational bottleneck.',
  },
  {
    id: 'arcesium-limina',
    logoKey: 'arcesium',
    date: '2 Feb 2026',
    dateSort: '2026-02-02',
    acquirer: 'Arcesium',
    target: 'Limina',
    status: 'Closed',
    acquirerType: 'Private (D.E. Shaw / Blackstone / JP Morgan-backed)',
    timeline: 'Fast (weeks)',
    dealLogic:
      'Create front-to-back operating platform for asset managers. Integrate Limina\'s portfolio & order management with Arcesium\'s middle/back-office.',
    pattern:
      'Demonstrates front-to-back consolidation logic. Limina handles investment mandate compliance (portfolio limits, concentration). FIXFriend handles connectivity-layer compliance (protocol changes, venue certification). Different domains, same M&A rationale.',
    relevance: null,
  },
  {
    id: 'broadridge-cqg',
    logoKey: 'broadridge',
    date: '6 Feb 2026',
    dateSort: '2026-02-06',
    acquirer: 'Broadridge',
    target: 'CQG',
    status: 'Expected close Jun 2026',
    acquirerType: 'Public (NYSE: BR)',
    timeline: '~4 months',
    dealLogic:
      'Add execution management, algos, analytics to existing OMS/connectivity stack. Third major acquisition in front-to-back buildout — after Itiviti (2021) and Acolin (2025).',
    pattern:
      'Broadridge now owns connectivity → order management → execution. Still missing: automated compliance validation and evidence across venue connections.',
    relevance:
      "Founder's edge: Owen Perry worked at both Itiviti and Broadridge, including directly with Tbricks and the BTCS stack (VeriFIX, NYFIX). Knows the gap firsthand.",
  },
  {
    id: 'marketaxess-rfqhub',
    logoKey: 'marketaxess',
    date: 'May 2025',
    dateSort: '2025-05-12',
    acquirer: 'MarketAxess',
    target: 'RFQ-hub',
    status: 'Closed',
    acquirerType: 'Public (NASDAQ: MKTX)',
    timeline: '~1 month',
    dealLogic:
      'Acquire 90% of RFQ-hub, a multi-asset RFQ platform for derivatives, structured products and ETFs. Expand electronic trading protocols and distribution via MarketAxess\'s global client network.',
    pattern:
      'Electronic trading protocol consolidation. RFQ-hub adds protocol and connectivity breadth; venue and protocol change management remains a compliance and operational burden for clients.',
    relevance: null,
  },
  {
    id: 'kkr-osttra',
    logoKey: 'kkr',
    date: 'Oct 2025',
    dateSort: '2025-10-10',
    acquirer: 'KKR',
    target: 'OSTTRA',
    status: 'Closed',
    acquirerType: 'Private Equity',
    timeline: '~6 months',
    dealValue: '~$3.1B',
    dealLogic:
      'Acquire post-trade solutions provider from S&P Global and CME Group. OSTTRA handles trade processing, lifecycle management and optimization across rates, FX, credit and equities.',
    pattern:
      'Post-trade infrastructure consolidation. Larger stacks mean more touchpoints and protocol dependencies; compliance evidence and change-control remain critical across the trade lifecycle.',
    relevance: null,
  },
  {
    id: 'six-baymarkets',
    logoKey: 'six',
    date: '25 Nov 2025',
    dateSort: '2025-11-25',
    acquirer: 'SIX Group',
    target: 'Baymarkets',
    status: 'Closed',
    acquirerType: 'Private (Swiss bank-owned)',
    timeline: '~3 months',
    dealLogic:
      'Strengthen pan-European clearing. Baymarkets (Oslo) provides clearing platform technology; SIX integrates clearing capabilities across derivatives and multiple asset classes.',
    pattern:
      'Exchange and clearing consolidation. SIX now operates multiple venues and clearing systems; member certification and connectivity compliance scale with each new platform.',
    relevance:
      'SIX already acquired Aquis (deal on timeline). More venues and clearing systems under one roof amplifies certification and protocol evidence needs.',
  },
  {
    id: 'tt-opengamma',
    logoKey: 'tt',
    date: '17 Dec 2025',
    dateSort: '2025-12-17',
    acquirer: 'Trading Technologies',
    target: 'OpenGamma',
    status: 'Closed',
    acquirerType: 'Private',
    timeline: '~2 months',
    dealLogic:
      'Integrate margin and capital optimization analytics into TT\'s execution and clearing stack. OpenGamma serves buy-side and sell-side; TT gains hedge fund and energy sector reach.',
    pattern:
      'Front-to-back derivatives stack. TT adds margin analytics to execution and clearing; compliance and evidence around protocol changes and venue certification remain manual.',
    relevance: null,
  },
]

export const INTERVIEW_TRACKER = [
  {
    id: 'tom-bloomberg',
    name: 'Tom',
    role: 'Senior engineer, EMS / connectivity (Broadway → Bloomberg)',
    company: 'Bloomberg',
    date: '2026-02',
    channel: 'Video call',
    userType: 'Vendor engineer / workflow owner',
    buyerInfluence: 'High — shapes estimates and feasibility, but not the contract signatory',
    economicBuyerSignal: 'Indirect — Bloomberg is a potential long-range acquirer archetype',
    painRatings: {
      communication: 'High',
      protocolFragmentation: 'High',
      testingAndSimulation: 'High',
      connectivityAndEnvironment: 'Medium',
      planningUncertainty: 'Medium',
      evidenceAndCertification: 'High',
    },
    currentSolutions: [
      'Manual relationship-driven communication with venues and clients',
      'Internal simulators for selected flows',
      'Per-venue normalisation logic and ad-hoc buffers in project plans',
    ],
    budgetAuthority: 'Influencer',
    workflowStages: ['trigger', 'triage', 'context', 'certification', 'rollout', 'evidence'],
    keyQuotes: [
      {
        label: 'Flagship',
        painPoint: 'protocolFragmentation',
        workflowStage: 'context',
        text:
          'We would receive a spec and probably end up finding bugs in the venue implementation, especially in the D2C space, so our cycle is much longer.',
      },
      {
        label: 'Communication drag',
        painPoint: 'communication',
        workflowStage: 'trigger',
        text:
          'Half the time the first real signal is a client forwarding a venue email that never came to us directly.',
      },
      {
        label: 'API sprawl',
        painPoint: 'protocolFragmentation',
        workflowStage: 'context',
        text:
          'FIX is supposed to be standard, but in practice you are juggling a dozen flavours and hundreds of custom tags just to get to “hello world”.',
      },
      {
        label: 'External QA',
        painPoint: 'testingAndSimulation',
        workflowStage: 'certification',
        text:
          'On some D2C integrations we effectively became the venue’s external QA team — we find the edge cases, they patch, and the clock keeps ticking.',
      },
      {
        label: 'Time-to-market buffer',
        painPoint: 'planningUncertainty',
        workflowStage: 'rollout',
        text:
          'With some venues we automatically pad the plan by a couple of weeks just for communication and iteration. Everyone pays that tax.',
      },
    ],
    followUp: [
      'Quantify how often certification windows slip because of venue-side defects versus internal delays.',
      'Understand how Bloomberg’s internal AI tools are starting to touch estimation and certification docs.',
    ],
  },
  {
    id: 'jim-nasdaq-vol-trader',
    name: 'Jim',
    role: 'Volatility trader & former Senior Director, European Equity Derivatives',
    company: 'NASDAQ (then), current buy-side desk',
    date: '2026-02',
    channel: 'Video call',
    userType: 'Desk-level user / risk owner',
    buyerInfluence: 'High — sets urgency and pushes for fixes, but not platform budget owner',
    economicBuyerSignal: 'Medium — reinforces why exchange groups and execution platforms care about rollout speed and reliability',
    painRatings: {
      communication: 'High',
      protocolFragmentation: 'Medium',
      testingAndSimulation: 'Medium',
      connectivityAndEnvironment: 'Medium',
      planningUncertainty: 'High',
      evidenceAndCertification: 'Medium',
    },
    currentSolutions: [
      'Over-provisioned buffers around major venue changes in risk and limits',
      'Manual playbooks and runbooks for big release weekends',
      'Escalation to senior venue and vendor contacts when slippage threatens P&L',
    ],
    budgetAuthority: 'Influencer',
    workflowStages: ['certification', 'rollout', 'evidence'],
    keyQuotes: [
      {
        label: 'Market structure drag',
        painPoint: 'planningUncertainty',
        workflowStage: 'rollout',
        text:
          'The issue is rarely the trade idea. It is the delay created when the venue, the protocol, or the release window changes faster than the desk can absorb it.',
      },
      {
        label: 'External dependency risk',
        painPoint: 'communication',
        workflowStage: 'trigger',
        text:
          'The painful part is that the first real risk is often outside the desk. Once exchange or vendor change lands late, the whole rollout becomes a coordination problem.',
      },
      {
        label: 'Evidence trust',
        painPoint: 'testingAndSimulation',
        workflowStage: 'certification',
        text:
          'A change is only real once the evidence is good enough for risk, operations, and the desk to trust it. Until then, everyone is still waiting.',
      },
      {
        label: 'Cost of slippage',
        painPoint: 'evidenceAndCertification',
        workflowStage: 'evidence',
        text:
          'By the time you add the buffer, the rework, and the sign-off loop, a small venue delay turns into a real cost item.',
      },
    ],
    followUp: [
      'Quantify P&L impact of delayed feature rollouts on the volatility desk.',
      'Clarify which parts of the certification flow traders would trust an agent system to touch.',
    ],
  },
  {
    id: 'igor-broadridge-connectivity',
    name: 'Igor',
    role: 'Principal Software Engineer & Market Connectivity Specialist',
    company: 'Broadridge',
    date: '2026-02',
    channel: 'Video call',
    userType: 'Connectivity engineer / integration owner',
    buyerInfluence: 'High — influences vendor selection and implementation feasibility',
    economicBuyerSignal: 'Indirect — validates the technical pain behind buy-versus-build decisions',
    painRatings: {
      communication: 'Medium',
      protocolFragmentation: 'High',
      testingAndSimulation: 'High',
      connectivityAndEnvironment: 'High',
      planningUncertainty: 'Medium',
      evidenceAndCertification: 'High',
    },
    currentSolutions: [
      'Venue-specific adapters and exception handling around standard FIX flows',
      'Manual review of specs, release notes, and edge-case behavior before implementation',
      'Regression harnesses and test credentials maintained per venue',
    ],
    budgetAuthority: 'Influencer',
    workflowStages: ['trigger', 'context', 'certification', 'evidence'],
    keyQuotes: [
      {
        label: 'Protocol nuance',
        painPoint: 'protocolFragmentation',
        workflowStage: 'context',
        text:
          'FIX is the starting point, not the answer. The real work is always in the venue quirks, session behaviour, and tag-level exceptions.',
      },
      {
        label: 'Environment friction',
        painPoint: 'connectivityAndEnvironment',
        workflowStage: 'trigger',
        text:
          'The time sink is often getting the same setup in test, UAT, and production so everyone is looking at the same thing.',
      },
      {
        label: 'Testing drag',
        painPoint: 'testingAndSimulation',
        workflowStage: 'certification',
        text:
          'A lot of the project time disappears into setup, credentials, and repeated edge-case testing rather than the actual implementation.',
      },
      {
        label: 'Operational memory',
        painPoint: 'evidenceAndCertification',
        workflowStage: 'evidence',
        text:
          'What teams really need is a way to capture the spec, the exceptions, and the proof in one place instead of reconstructing it each time.',
      },
    ],
    followUp: [
      'Check whether a structured change pack would reduce the back-and-forth during implementation reviews.',
      'Validate how much of the evidence trail could be generated from existing logs and release artifacts.',
    ],
  },
  {
    id: 'arkady-squarepoint',
    name: 'Arkady',
    role: 'Business Analyst, electronic trading / quantitative strategies',
    company: 'Squarepoint',
    date: '2026-02',
    channel: 'Video call',
    userType: 'Workflow and requirements owner between quants, engineers, and trading',
    buyerInfluence: 'High — defines workflows and owns the backlog, strong internal champion',
    economicBuyerSignal: 'Indirect — confirms buy-side demand for better venue-change governance',
    painRatings: {
      communication: 'Medium',
      protocolFragmentation: 'High',
      testingAndSimulation: 'High',
      connectivityAndEnvironment: 'Medium',
      planningUncertainty: 'High',
      evidenceAndCertification: 'High',
    },
    currentSolutions: [
      'Jira/Confluence templates for venue-change epics and tasks',
      'Spreadsheet-based matrices mapping venues, symbols, and strategy impact',
      'Hand-built regression packs maintained per venue and per strategy family',
    ],
    budgetAuthority: 'Influencer',
    workflowStages: ['triage', 'context', 'certification', 'evidence'],
    keyQuotes: [
      {
        label: 'Context fragmentation',
        painPoint: 'protocolFragmentation',
        workflowStage: 'context',
        text:
          'Most of the work is translating a dense venue note into something quants, engineers, and trading can all act on without losing the edge cases.',
      },
      {
        label: 'Backlog multiplication',
        painPoint: 'planningUncertainty',
        workflowStage: 'triage',
        text:
          'A single change notice turns into config, risk checks, regression scope, and client comms. That extra work is never visible in the first email.',
      },
      {
        label: 'Evidence reconstruction',
        painPoint: 'evidenceAndCertification',
        workflowStage: 'evidence',
        text:
          'When compliance asks for proof, we are still stitching together Jira, logs, and screenshots after the fact.',
      },
      {
        label: 'Automation opportunity',
        painPoint: 'testingAndSimulation',
        workflowStage: 'certification',
        text:
          'If AI can draft the first pass with the right context attached, it would remove a lot of the coordination overhead before testing even starts.',
      },
    ],
    followUp: [
      'Test whether an agent-generated change pack would be trusted as the first draft of a Jira epic and regression scope.',
      'Understand how much of the current evidence pack could be automated from existing logs and artifacts.',
    ],
  },
  {
    id: 'david-furlong-virtu',
    name: 'David Furlong',
    role: 'CEO',
    company: 'Virtu Europe',
    date: '2026-03',
    channel: 'Discovery call',
    userType: 'Economic buyer / strategic signal',
    buyerInfluence: 'High — strategic buyer signal and structural pain validation',
    economicBuyerSignal: 'High — validates external infrastructure cost and control burden',
    painRatings: {
      communication: 'High',
      protocolFragmentation: 'Medium',
      testingAndSimulation: 'Medium',
      connectivityAndEnvironment: 'Medium',
      planningUncertainty: 'High',
      evidenceAndCertification: 'High',
    },
    currentSolutions: [
      'Heavier diligence before introducing new vendors into sensitive workflows',
      'Relying on external infrastructure teams and manual oversight across exchange, market data, and post-trade constraints',
      'Structured internal review before anything touches a live rollout',
    ],
    budgetAuthority: 'Economic buyer',
    workflowStages: ['strategy', 'triage', 'evidence'],
    keyQuotes: [
      {
        label: 'External constraint',
        painPoint: 'communication',
        workflowStage: 'triage',
        text:
          'The biggest problems are usually external. Internal systems are fine until the exchange, market data, or post-trade landscape becomes the constraint.',
      },
      {
        label: 'Trust boundary',
        painPoint: 'evidenceAndCertification',
        workflowStage: 'evidence',
        text:
          'You do not put a new vendor into a sensitive workflow unless it is already proven, bounded, and auditable.',
      },
    ],
    followUp: [
      'Quantify the cost of external infrastructure constraints across trading and post-trade workflows.',
      'Test how much proof is needed before an internal team trusts a new workflow layer.',
    ],
  },
  {
    id: 'ben-ernest-jones-quod',
    name: 'Ben Ernest-Jones',
    role: 'Chief Product & Technology Officer',
    company: 'Quod Financial',
    date: '2026-03',
    channel: 'Discovery call',
    userType: 'Product buyer / strategic signal',
    buyerInfluence: 'High — strong product-side sponsor and workflow owner signal',
    economicBuyerSignal: 'Medium — validates buyer urgency around QA, handoff, and context fragmentation',
    painRatings: {
      communication: 'High',
      protocolFragmentation: 'Medium',
      testingAndSimulation: 'High',
      connectivityAndEnvironment: 'Medium',
      planningUncertainty: 'High',
      evidenceAndCertification: 'Medium',
    },
    currentSolutions: [
      'Meetings, chat threads, email, and AI tools stitched together manually',
      'QA and handoff reviews spread across multiple systems and people',
      'Ad hoc context gathering before development and testing',
    ],
    budgetAuthority: 'Influencer',
    workflowStages: ['triage', 'context', 'certification'],
    keyQuotes: [
      {
        label: 'Bottleneck',
        painPoint: 'testingAndSimulation',
        workflowStage: 'certification',
        text: 'QA is the primary bottleneck, not coding.',
      },
      {
        label: 'Fragmented context',
        painPoint: 'communication',
        workflowStage: 'triage',
        text:
          'We are still copying and pasting context between meetings, chat, email, and AI tools instead of giving the system one working bundle.',
      },
    ],
    followUp: [
      'See whether a bundled working context would reduce QA and handoff delays.',
      'Test if the team would trust AI-assisted output once the context is assembled in one place.',
    ],
  },
  {
    id: 'bjorn-haggstrom',
    name: 'Bjorn Haggstrom',
    role: 'Former EMEA Customer Success & Operations leader',
    company: 'Independent operator / advisor',
    date: '2026-02',
    channel: 'Demo + interview',
    userType: 'Operator / strategic advisor',
    buyerInfluence: 'Medium — validates operational pain and acquisition-fit signal',
    economicBuyerSignal: 'Medium — suggests the capability may be bought as a workflow layer rather than built',
    painRatings: {
      communication: 'Medium',
      protocolFragmentation: 'Medium',
      testingAndSimulation: 'Medium',
      connectivityAndEnvironment: 'Medium',
      planningUncertainty: 'High',
      evidenceAndCertification: 'High',
    },
    currentSolutions: [
      'Experience-led client support and manual upgrade coordination',
      'Ad hoc process fixes for software instability and complex releases',
      'Workarounds instead of a systematic client self-service layer',
    ],
    budgetAuthority: 'Influencer',
    workflowStages: ['context', 'certification', 'rollout'],
    keyQuotes: [
      {
        label: 'Recurring pain',
        painPoint: 'planningUncertainty',
        workflowStage: 'rollout',
        text: 'The recurring pains are software instability, complex upgrades, and lack of client self-service.',
      },
      {
        label: 'Acquisition signal',
        painPoint: 'evidenceAndCertification',
        workflowStage: 'context',
        text: 'This looks more like something a larger firm would buy to get the capability faster than build internally.',
      },
    ],
    followUp: [
      'Test which parts of the workflow are most suitable for an embedded capability.',
      'See how much of the upgrade and support burden can be compressed into a repeatable workflow.',
    ],
  },
  {
    id: 'miles-asset-manager',
    name: 'Miles',
    role: 'Asset manager',
    company: 'WCM Investment Management',
    date: '2026-03',
    channel: 'TBD',
    userType: 'Pending interview',
    buyerInfluence: 'Unknown',
    economicBuyerSignal: 'Unknown',
    painRatings: {},
    currentSolutions: [],
    budgetAuthority: 'TBD',
    workflowStages: [],
    status: 'Call scheduled',
    note: 'Chief of Staff at a $100B+ AUM asset manager. Planned conversation to test whether the same workflow-control pain shows up in asset-management operating and change workflows, outside the trading software vendor lens.',
    followUp: ['Discovery call scheduled.'],
  },
]
